import React, { useEffect, useState } from 'react'
import HomeOverview from './HomeOverview.jsx'
import { supabase, getMyWorkspaces } from './lib/supabase.js'

function legacyHomeVisible(){const root=document.getElementById('root');if(!root)return false;return [...root.querySelectorAll('h1')].some(el=>(el.textContent||'').trim()==='Practice Hub')}
function hideLegacyHome(){const root=document.getElementById('root');if(!root)return;const heading=[...root.querySelectorAll('h1')].find(el=>(el.textContent||'').trim()==='Practice Hub');if(!heading)return;let n=heading;while(n&&n.parentElement&&n.parentElement!==root){const s=getComputedStyle(n);if(s.flexGrow==='1'&&s.overflowY==='auto'){n.classList.add('tf-home-legacy');return}n=n.parentElement}}
function applyNav(home){const nav=document.querySelector('nav');if(!nav)return;if(home){if(nav.children[2])nav.children[2].classList.add('tf-home-nav-separator');if(nav.children[3])nav.children[3].classList.add('tf-home-nav-workspaces');nav.querySelectorAll('button,[role="button"]').forEach(el=>{const label=(el.innerText||el.textContent||'').toLowerCase(),title=(el.getAttribute('title')||'').toLowerCase();if(label.includes('install app')||label.includes('client portal')||title.includes('announcements')||title.includes('attendance'))el.classList.add('tf-home-secondary-action')})}else{nav.querySelectorAll('.tf-home-nav-separator,.tf-home-nav-workspaces').forEach(el=>el.classList.remove('tf-home-nav-separator','tf-home-nav-workspaces'));nav.querySelectorAll('.tf-home-secondary-action').forEach(el=>el.classList.remove('tf-home-secondary-action'))}}
function clickOriginalText(text,prefer=''){const root=document.getElementById('root');if(!root)return;const nodes=[...root.querySelectorAll('*')].filter(el=>(el.textContent||'').trim()===text);const node=nodes.find(el=>!prefer||((el.parentElement?.textContent||'').includes(prefer)))||nodes[0];if(node)node.click()}
function clickOriginalByTitle(part){const root=document.getElementById('root');if(!root)return;const node=[...root.querySelectorAll('[title]')].find(el=>(el.getAttribute('title')||'').toLowerCase().includes(part.toLowerCase()));if(node)node.click()}
function addHomeMoreItems(){const root=document.getElementById('root');if(!root)return;const menu=[...root.querySelectorAll('div')].find(el=>{const t=(el.textContent||'');return t.includes('Quick Notes')&&t.includes('Support')&&t.includes('Light mode')&&getComputedStyle(el).position==='absolute'});if(!menu||menu.querySelector('[data-tf-home-extra]'))return;const items=[['Install app',()=>clickOriginalText('Install app')],['Client Portal',()=>clickOriginalText('Client Portal')],['Announcements',()=>clickOriginalByTitle('announcements')],['Attendance',()=>clickOriginalByTitle('attendance')]];items.forEach(([label,fn])=>{const b=document.createElement('button');b.type='button';b.dataset.tfHomeExtra='1';b.textContent=label;b.style.cssText='width:100%;text-align:left;display:flex;align-items:center;gap:10px;padding:10px 14px;border:none;border-top:1px solid var(--tf-border);background:transparent;cursor:pointer;font-family:inherit;font-size:13px;font-weight:600;color:var(--tf-text)';b.onmouseenter=()=>{b.style.background='var(--tf-surface)'};b.onmouseleave=()=>{b.style.background='transparent'};b.onclick=()=>{fn();setTimeout(()=>menu.querySelector('[data-tf-home-extra]')?.blur(),0)};menu.appendChild(b)})}
export default function HomeSkin(){
  const [home,setHome]=useState(false),[data,setData]=useState({orgs:[],workspaces:[],profiles:[],user:null})
  async function loadData(){const auth=await supabase.auth.getUser(),user=auth.data?.user;if(!user){setData({orgs:[],workspaces:[],profiles:[],user:null});return}const [or,wr,pr]=await Promise.all([supabase.from('organizations').select('*').order('name').limit(100),getMyWorkspaces(user.id),supabase.from('profiles').select('id,name,email').limit(500)]);setData({orgs:or.data||[],workspaces:wr.data||[],profiles:pr.data||[],user})}
  useEffect(()=>{let raf=0;const schedule=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const h=legacyHomeVisible();setHome(h);if(h)hideLegacyHome();applyNav(h)})};const observer=new MutationObserver(schedule);observer.observe(document.body,{childList:true,subtree:true});const click=e=>{const b=e.target?.closest?.('button');if(b&&(b.getAttribute('title')||'').toLowerCase()==='more')setTimeout(addHomeMoreItems,0)};document.addEventListener('click',click);window.addEventListener('resize',schedule);schedule();loadData();return()=>{cancelAnimationFrame(raf);observer.disconnect();document.removeEventListener('click',click);window.removeEventListener('resize',schedule)}},[])
  useEffect(()=>{if(home){document.body.classList.add('tf-home-active');hideLegacyHome();applyNav(true)}else{document.body.classList.remove('tf-home-active');applyNav(false)}},[home])
  if(!home)return null
  return <div className="tf-home-overlay"><HomeOverview orgs={data.orgs} workspaces={data.workspaces} allProfiles={data.profiles} supabase={supabase} cu={data.user} onOpenOrg={org=>clickOriginalText(org.name,'Space')} onOpenWorkspace={ws=>clickOriginalText(ws.name,ws.description||'')} onCreateOrg={()=>clickOriginalText('+ New Practice')}/></div>
}
